# Generated by Django 6.0 on 2026-01-03 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^UC\\d+$'), django.core.validators.MinLengthValidator(12)], verbose_name='ID do canal')),
                ('canal_nome', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome do canal')),
                ('canal_inscritos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inscritos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Categoria')),
                ('palavras_chave', models.CharField(max_length=130, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Palavras chave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Playlist ID')),
                ('playlist_nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator(regex='^PL\\d+$')], verbose_name='Nome da Playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Video ID')),
                ('url', models.CharField(max_length=43, unique=True, validators=[django.core.validators.MinLengthValidator(43)], verbose_name='URL')),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Titulo')),
                ('likes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Likes')),
                ('deslikes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deslikes')),
                ('salvos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salvos')),
                ('downloads', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Downloads')),
                ('duracao', models.TimeField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(4000000000)], verbose_name='Duração')),
                ('comentarios', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comentários')),
                ('descricao', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Descrição do vídeo')),
                ('data_postagem', models.DateField(verbose_name='Data do video')),
                ('qualidade_px', models.CharField(choices=[('P360', '360'), ('P480', '480'), ('P720', '720'), ('P1080', '1080'), ('P1440', '1440'), ('P2160', '2160')], max_length=5, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Qualidade')),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'PUBLICO'), ('PRIVADO', 'PRIVADO')], max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Visibilidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
