# Generated by Django 6.0 on 2026-01-03 17:58

import django.core.validators
import youtube.validators.validar_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='idioma',
            field=models.CharField(default=223, max_length=5, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Idioma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='data_postagem',
            field=models.DateField(validators=[youtube.validators.validar_data.ValidarData()], verbose_name='Data do video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duracao',
            field=models.TimeField(verbose_name='Duração'),
        ),
    ]
