# Generated by Django 6.0 on 2026-01-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_video_idioma_alter_video_data_postagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='canal',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='youtube.canal', verbose_name='Canal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='youtube.categoria', verbose_name='Categorias'),
        ),
    ]
